In [2]:
import pandas as pd

In [ ]:
#extract csv from a url
#url= https://www.football-data.co.uk/data.php

In [5]:
prem_23= pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/E0.csv")

In [6]:
prem_23.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88

In [7]:
prem_23.rename(columns={'FTAG': 'away_goals',
                       'FTHG':'home_goals'}, inplace=True)

In [8]:
prem_23.columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'home_goals',
       'away_goals', 'FTR', 'HTHG', 'HTAG',
       ...
       'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH',
       'MaxCAHA', 'AvgCAHH', 'AvgCAHA'],
      dtype='object', length=106)

In [9]:
prem_23

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,E0,29/10/2023,13:00,West Ham,Everton,0,1,A,0,0,...,2.14,-0.50,2.09,1.84,2.09,1.85,2.10,1.86,2.06,1.82
96,E0,29/10/2023,14:00,Aston Villa,Luton,3,1,H,1,0,...,2.74,-1.50,1.97,1.96,1.97,1.94,1.98,2.06,1.92,1.95
97,E0,29/10/2023,14:00,Brighton,Fulham,1,1,D,1,0,...,2.29,-1.00,2.05,1.88,2.08,1.85,2.12,1.98,2.02,1.85
98,E0,29/10/2023,14:00,Liverpool,Nott'm Forest,3,0,H,2,0,...,2.79,-1.75,1.93,2.00,1.84,2.08,1.93,2.16,1.83,2.03
99,E0,29/10/2023,15:30,Man United,Man City,0,3,A,0,1,...,2.23,1.00,1.91,2.02,1.88,2.05,1.97,2.12,1.86,2.02